#!/bin/bash

export JAVA_HOME=$(pwd)/jdk/jdk-21.0.6
export PATH=$JAVA_HOME/bin:$PATH

mkdir -p out

SRC=$(dirname "$0")

javac -cp $SRC/lib/*:. -d out $(find $SRC -name "*.java")
java -cp $SRC/lib/*:out:. Main "$@"

