#!/bin/bash

cd "$(dirname "$0")/.." || exit

export JAVA_HOME=$(pwd)/jdk/jdk-21.0.6
export PATH=$JAVA_HOME/bin:$PATH

mkdir -p out

echo $(ls -al)

jdk/jdk-21.0.6/bin/javac -cp lib/*:. -d out $(find ./src -name "*.java")
jdk/jdk-21.0.6/bin/java -cp lib/*:out:. Main "$@"
